backend = "wal"
color_space = "lch"
palette = "dark"
check_contrast = true

[templates]
css3 = { template = 'gtk-css.css', target = '~/.config/gtk-3.0/colors.css' }
css4 = { template = 'gtk-css.css', target = '~/.config/gtk-4.0/colors.css' }
pywalfox = { template = 'colors.json', target = '~/.cache/wal/colors.json' }
waybar = { template = 'waybar.css', target = '~/.config/colors/colors.css' }
kitty = { template = 'kitty.conf', target = '~/.config/kitty/themes/Wallust.conf' }
hyprland = { template = 'hyprland.conf', target = '~/.config/colors/hyprcolors.conf' }

