format = """
(bold blue)$directory$git_branch$git_status$git_state
$character"""

command_timeout = 1000

[character]
success_symbol = "[󰘧](bold blue)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[󰘧](bold blue)"

[username]
disabled = true

[hostname]
disabled = true

[directory]
truncation_length = 4
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold cyan"
read_only = "  "
home_symbol = "~"
truncation_symbol = "…/"

[directory.substitutions]

[git_branch]
symbol = " "
format = " [$branch(:$remote_branch) $symbol]($style)"
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "bold yellow"
conflicted = "⚔"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "◌${count}"
stashed = "󰏖"
modified = "●${count}"
staged = "✚${count}"
renamed = "➜${count}"
deleted = "✖${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

[nodejs]
symbol = "󰎙 "
format = " [$symbol$version]($style)"
style = "bold green"

[python]
symbol = " "
format = ' [$symbol$version(\($virtualenv\))]($style)'
style = "bold yellow"

[rust]
symbol = " "
format = " [$symbol$version]($style)"
style = "bold red"

[golang]
symbol = "󰟓 "
format = " [$symbol$version]($style)"
style = "bold cyan"

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"
style = "bold blue"

[package]
symbol = "󰏗 "
format = " [$symbol$version]($style)"
style = "208"

[time]
disabled = false
format = " [$time]($style)"
style = "bold white"
time_format = "%T"

[cmd_duration]
min_time = 500
format = " 󰔛[$duration]($style)"
style = "bold yellow"

[memory_usage]
disabled = true
threshold = 75
symbol = "󰍛 "
format = " $symbol[$ram( | $swap)]($style)"
style = "bold dimmed white"

[aws]
symbol = " "
format = ' [$symbol$profile(\($region\))]($style)'
style = "bold yellow"

[kubernetes]
symbol = "󱃾 "
format = ' [$symbol$context( \($namespace\))]($style)'
style = "bold cyan"
disabled = false
