[colors.primary]
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.cursor]
text = '{{colors.on_surface_variant.default.hex}}'
cursor = '{{colors.on_surface.default.hex}}'

[colors.selection]
text = '{{colors.on_secondary.default.hex}}'
background = '{{colors.secondary_fixed_dim.default.hex}}'

[colors.search.matches]
foreground = '{{colors.surface_variant.default.hex}}'
background = '{{colors.primary.default.hex}}'

[colors.search.focused_match]
foreground = '{{colors.surface_variant.default.hex}}'
background = '{{colors.primary.default.hex}}'

[colors.footer_bar]
foreground = '{{colors.surface_variant.default.hex}}'
background = '{{colors.inverse_surface.default.hex}}'

[colors.hints.start]
foreground = '{{colors.surface_variant.default.hex}}'
background = '{{colors.secondary.default.hex}}'

[colors.hints.end]
foreground = '{{colors.surface_variant.default.hex}}'
background = '{{colors.secondary.default.hex}}'


[colors.normal]
black   = '#4c4c4c'                         # color0
red     = '#ac8a8c'                         # color1
green   = '#8aac8b'                         # color2
yellow  = '#aca98a'                         # color3
blue    = '{{colors.primary.default.hex}}'    # color4
magenta = '#ac8aac'  # color5
cyan    = '#8aacab'                         # color6
white   = '#f0f0f0'                         # color7


[colors.bright]
black   = '#262626'                         # color8
red     = '#c49ea0'                         # color9
green   = '#9ec49f'                         # color10
yellow  = '#c4c19e'                         # color11
blue    = '#a39ec4'                         # color12
magenta = '#c49ec4'                         # color13
cyan    = '#9ec3c4'                         # color14
white   = '#e7e7e7'                         # color15
